#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 13 11:23:15 2023

@author: santi
"""

#%%


import numpy as np
import matplotlib.pyplot as plt



num_steps = 1000
dt = 10  # fs
times = np.arange(num_steps)*dt

Rand = np.random.rand(times.size)

jj=0
for ii in range(int(num_steps/10)):
    t = times[jj:jj+10]
    
    A = (1+np.random.rand()*0.5) * 1
    w = (1+np.random.rand()*0.1) * 2*np.pi/10
    B = (1+np.random.rand()*0.1) * 100
    
    Rand[jj:jj+10] = Rand[jj:jj+10] +  A * np.sin(w*t) + B
    jj+=10
    
plt.figure(1)
plt.plot(times, Rand, 'o-')


#%%
tmax = times[-1]
acf = np.zeros(times.size)
for ii in range(times.size):    
    tau = ii*dt
    jj, t0, acf_ii = 0, 0, 0
    while t0+tau<=tmax:
        print(f"tau = {tau} ps, t0 = {t0} ps, ---------{jj}")                
        acf_ii += Rand[ii+jj]*Rand[jj]
        jj+=1
        t0 = jj*dt
    # print(f"tau = {tau} ps, t0_max = {t0} fs, ---------")                        
    print(f"el promedio es dividir por {jj}")
    acf[ii] = acf_ii/jj
    
plt.figure(2)
plt.plot(times, acf, 'ro-')